### ISSUE TITLE
R version 3.5 apt repositories do not resolve using ansible_distribution_release in cran_apt_repo

### ISSUE THREAD

**Issue by grosscol** [andrewrothstein/ansible-r#1]
The cran_apt_repo default specified in debian and ubuntu vars does not work for distributions that have R 3.5 as the repo name has "-cran35" appened to the distribution name e.g. "stretch-cran35" or "bionic-cran35".
https://github.com/andrewrothstein/ansible-r/blob/022541472f56799cc31432d432dca7b3d15a52a4/vars/Debian.yml#L5

workaround is to override the `cran_apt_repo` 
```yaml
- hosts: rapphosts
  roles:
    - role: andrewrothstein.r
      vars:
        cran_apt_repo: 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
        r_pkgs:
          - dplyr
          - ggplot2
```
